[package]
name = "unicode-language"
version = "2.3.0"
edition = "2024"
license = "Apache-2.0"
authors = ["Bram Stein <b.l.stein@gmail.com>"]
description = "A library to detect language coverage given a list of codepoints."
documentation = "https://docs.rs/unicode-language"
homepage = "https://github.com/the-type-founders/unicode-language-rs"
repository = "https://github.com/the-type-founders/unicode-language-rs"
categories = ["text-processing"]
keywords = ["unicode", "language"]
build = "build.rs"

[lib]
name = "unicode_language"
path = "src/lib.rs"

[build-dependencies]
glob = "0.3"
serde = { version = "1", features = ["derive"] }
serde-saphyr = { version = "1", default-features = false, features = ["deserialize"] }
langtag = "1"
